name: OTLP Log Processor Backend Go
on:
  push:
    branches:
      - main
    paths:
      - 'otlp-log-processor-backend-go/**'
  pull_request:
    paths:
      - 'otlp-log-processor-backend-go/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
      - run: go build ./...
        working-directory: 'otlp-log-processor-backend-go'
      - run: go test ./...
        working-directory: 'otlp-log-processor-backend-go'
